[[redirects]]
  from = "/js/index.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true

[[redirects]]
  from = "/images"
  to = "/"
  status = 301
  force = true